# Form implementation generated from reading ui file './graphics/app_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# pyuic6 -x ./graphics/app_window.ui -o ./graphics/app_window.py
import sys
from pathlib import Path

from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(991, 580)
        self.progress_bar = QtWidgets.QProgressBar(parent=main_window)
        self.progress_bar.setGeometry(QtCore.QRect(20, 190, 951, 23))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.btn_compress = QtWidgets.QPushButton(parent=main_window)
        self.btn_compress.setGeometry(QtCore.QRect(20, 120, 81, 41))
        self.btn_compress.setObjectName("btn_compress")
        self.btn_lzw = QtWidgets.QRadioButton(parent=main_window)
        self.btn_lzw.setGeometry(QtCore.QRect(20, 80, 52, 22))
        self.btn_lzw.setObjectName("btn_lzw")
        self.btn_huffman = QtWidgets.QRadioButton(parent=main_window)
        self.btn_huffman.setGeometry(QtCore.QRect(20, 43, 78, 22))
        self.btn_huffman.setObjectName("btn_huffman")
        self.log_label_field = QtWidgets.QLineEdit(parent=main_window)
        self.log_label_field.setGeometry(QtCore.QRect(20, 270, 951, 291))
        self.log_label_field.setObjectName("log_label_field")
        self.log_label = QtWidgets.QLabel(parent=main_window)
        self.log_label.setGeometry(QtCore.QRect(20, 234, 58, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.log_label.setFont(font)
        self.log_label.setObjectName("log_label")
        self.btn_choose_input_file = QtWidgets.QPushButton(parent=main_window)
        # self.btn_choose_input_file.setText("Open file dialog")
        self.btn_choose_input_file.clicked.connect(self.open_file_dialog)



        self.btn_choose_input_file.setGeometry(QtCore.QRect(200, 40, 80, 31))
        self.btn_choose_input_file.setObjectName("btn_choose_input_file")
        self.btn_choose_output_file = QtWidgets.QPushButton(parent=main_window)
        self.btn_choose_output_file.setGeometry(QtCore.QRect(200, 90, 80, 31))
        self.btn_choose_output_file.setObjectName("btn_choose_output_file")
        self.input_file_field = QtWidgets.QPlainTextEdit(parent=main_window)
        self.input_file_field.setGeometry(QtCore.QRect(300, 40, 671, 31))
        self.input_file_field.setObjectName("input_file_field")
        self.output_file_field = QtWidgets.QPlainTextEdit(parent=main_window)
        self.output_file_field.setGeometry(QtCore.QRect(300, 90, 671, 31))
        self.output_file_field.setObjectName("output_file_field")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "File Compressor"))
        self.btn_compress.setText(_translate("main_window", "Compress"))
        self.btn_lzw.setText(_translate("main_window", "LZW"))
        self.btn_huffman.setText(_translate("main_window", "Huffman"))
        self.log_label.setText(_translate("main_window", "Log"))
        self.btn_choose_input_file.setText(_translate("main_window", "Choose file"))
        self.btn_choose_output_file.setText(_translate("main_window", "Choose file"))

    def open_file_dialog(self):
        home_dir = str(Path.home())
        fname = QFileDialog.getOpenFileName(main_window, 'Open file', home_dir)
        if fname[0]:
            f = open(fname[0], 'r')
            with f:
                data = f.read()
                self.textEdit.setText(data)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QWidget()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec())
