# Form implementation generated from reading ui file './graphics/app_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# pyuic6 -x ./graphics/app_window.ui -o ./graphics/app_window.py


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(991, 580)
        self.progressBar = QtWidgets.QProgressBar(parent=form)
        self.progressBar.setGeometry(QtCore.QRect(20, 190, 951, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(parent=form)
        self.pushButton.setGeometry(QtCore.QRect(20, 120, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=form)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 80, 52, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=form)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 43, 78, 22))
        self.radioButton_3.setObjectName("radioButton_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 270, 951, 291))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=form)
        self.label.setGeometry(QtCore.QRect(20, 234, 58, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(parent=form)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 40, 80, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=form)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 90, 80, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=form)
        self.plainTextEdit.setGeometry(QtCore.QRect(300, 40, 671, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(parent=form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(300, 90, 671, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "File Compressor"))
        self.pushButton.setText(_translate("form", "Compress"))
        self.radioButton_2.setText(_translate("form", "LZW"))
        self.radioButton_3.setText(_translate("form", "Huffman"))
        self.label.setText(_translate("form", "Log"))
        self.pushButton_2.setText(_translate("form", "Choose file"))
        self.pushButton_3.setText(_translate("form", "Choose file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec())
